[package]
name = "audio-client"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
audio-core = { path = "../../crates/audio-core" }
metrics = { path = "../../crates/metrics" }
protocol = { path = "../../crates/protocol" }
tokio.workspace = true
webrtc-ice.workspace = true
webrtc-util.workspace = true
windows-sys.workspace = true
windows.workspace = true
ropus.workspace = true
chacha20poly1305.workspace = true
hkdf.workspace = true
rand_core.workspace = true
sha2.workspace = true
x25519-dalek.workspace = true
