-- =====================================================================
-- songs 더미 데이터 200건
--
--  - song_id 12 ~ 211 (기존 데이터 2~11 과 충돌하지 않도록 12부터 시작)
--  - object key / thumbnail 은 기존 데이터와 동일한 규칙(songs/{id}/...)으로 생성
--  - 실제 S3 파일은 존재하지 않는 더미이므로 재생/분석 테스트에는 쓸 수 없음
--  - 기존 보유 음원(테이블 9건 + 별도 목록 17건)은 제외함
-- =====================================================================

INSERT INTO songs
(song_id, title, artist, duration, difficulty_level, thumbnail_image_url, mr_object_key, midi_object_key, lyrics_object_key, created_at)
VALUES
-- ---------- 레전드 / 포크·발라드 ----------
(12,  '서른 즈음에',                '김광석',                256, 4, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/12/cover.jpg',  'songs/12/mr.mp3',  'songs/12/midi.json',  'songs/12/lyrics.txt',  NOW(6)),
(13,  '이등병의 편지',              '김광석',                285, 4, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/13/cover.jpg',  'songs/13/mr.mp3',  'songs/13/midi.json',  'songs/13/lyrics.txt',  NOW(6)),
(14,  '붉은 노을',                  '이문세',                268, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/14/cover.jpg',  'songs/14/mr.mp3',  'songs/14/midi.json',  'songs/14/lyrics.txt',  NOW(6)),
(15,  '광화문 연가',                '이문세',                255, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/15/cover.jpg',  'songs/15/mr.mp3',  'songs/15/midi.json',  'songs/15/lyrics.txt',  NOW(6)),
(16,  '옛사랑',                     '이문세',                291, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/16/cover.jpg',  'songs/16/mr.mp3',  'songs/16/midi.json',  'songs/16/lyrics.txt',  NOW(6)),
(17,  '그 겨울의 찻집',             '조용필',                245, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/17/cover.jpg',  'songs/17/mr.mp3',  'songs/17/midi.json',  'songs/17/lyrics.txt',  NOW(6)),
(18,  '단발머리',                   '조용필',                218, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/18/cover.jpg',  'songs/18/mr.mp3',  'songs/18/midi.json',  'songs/18/lyrics.txt',  NOW(6)),
(19,  '돌아와요 부산항에',          '조용필',                205, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/19/cover.jpg',  'songs/19/mr.mp3',  'songs/19/midi.json',  'songs/19/lyrics.txt',  NOW(6)),
(20,  '서쪽 하늘',                  '이승철',                296, 8, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/20/cover.jpg',  'songs/20/mr.mp3',  'songs/20/midi.json',  'songs/20/lyrics.txt',  NOW(6)),
(21,  '그런 사람 또 없습니다',      '이승철',                279, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/21/cover.jpg',  'songs/21/mr.mp3',  'songs/21/midi.json',  'songs/21/lyrics.txt',  NOW(6)),
(22,  'J에게',                      '이선희',                224, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/22/cover.jpg',  'songs/22/mr.mp3',  'songs/22/midi.json',  'songs/22/lyrics.txt',  NOW(6)),
(23,  '인연',                       '이선희',                251, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/23/cover.jpg',  'songs/23/mr.mp3',  'songs/23/midi.json',  'songs/23/lyrics.txt',  NOW(6)),
(24,  '너를 위해',                  '임재범',                271, 8, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/24/cover.jpg',  'songs/24/mr.mp3',  'songs/24/midi.json',  'songs/24/lyrics.txt',  NOW(6)),
(25,  '고해',                       '임재범',                288, 9, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/25/cover.jpg',  'songs/25/mr.mp3',  'songs/25/midi.json',  'songs/25/lyrics.txt',  NOW(6)),
(26,  '비상',                       '임재범',                305, 9, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/26/cover.jpg',  'songs/26/mr.mp3',  'songs/26/midi.json',  'songs/26/lyrics.txt',  NOW(6)),
(27,  '보이지 않는 사랑',           '신승훈',                302, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/27/cover.jpg',  'songs/27/mr.mp3',  'songs/27/midi.json',  'songs/27/lyrics.txt',  NOW(6)),
(28,  'I Believe',                  '신승훈',                279, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/28/cover.jpg',  'songs/28/mr.mp3',  'songs/28/midi.json',  'songs/28/lyrics.txt',  NOW(6)),
(29,  '희망사항',                   '변진섭',                235, 3, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/29/cover.jpg',  'songs/29/mr.mp3',  'songs/29/midi.json',  'songs/29/lyrics.txt',  NOW(6)),
(30,  '그대에게',                   '무한궤도',              245, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/30/cover.jpg',  'songs/30/mr.mp3',  'songs/30/midi.json',  'songs/30/lyrics.txt',  NOW(6)),
(31,  '걱정말아요 그대',            '전인권',                268, 4, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/31/cover.jpg',  'songs/31/mr.mp3',  'songs/31/midi.json',  'songs/31/lyrics.txt',  NOW(6)),

-- ---------- 2000년대 발라드 / R&B ----------
(32,  '눈의 꽃',                    '박효신',                278, 8,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/32/cover.jpg',  'songs/32/mr.mp3',  'songs/32/midi.json',  'songs/32/lyrics.txt',  NOW(6)),
(33,  '야생화',                     '박효신',                289, 10, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/33/cover.jpg',  'songs/33/mr.mp3',  'songs/33/midi.json',  'songs/33/lyrics.txt',  NOW(6)),
(34,  '숨',                         '박효신',                300, 9,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/34/cover.jpg',  'songs/34/mr.mp3',  'songs/34/midi.json',  'songs/34/lyrics.txt',  NOW(6)),
(35,  '두 사람',                    '성시경',                258, 5,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/35/cover.jpg',  'songs/35/mr.mp3',  'songs/35/midi.json',  'songs/35/lyrics.txt',  NOW(6)),
(36,  '너의 모든 순간',             '성시경',                253, 7,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/36/cover.jpg',  'songs/36/mr.mp3',  'songs/36/midi.json',  'songs/36/lyrics.txt',  NOW(6)),
(37,  '희재',                       '성시경',                284, 8,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/37/cover.jpg',  'songs/37/mr.mp3',  'songs/37/midi.json',  'songs/37/lyrics.txt',  NOW(6)),
(38,  '보고싶다',                   '김범수',                267, 9,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/38/cover.jpg',  'songs/38/mr.mp3',  'songs/38/midi.json',  'songs/38/lyrics.txt',  NOW(6)),
(39,  '하루',                       '김범수',                259, 8,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/39/cover.jpg',  'songs/39/mr.mp3',  'songs/39/midi.json',  'songs/39/lyrics.txt',  NOW(6)),
(40,  '제발',                       '이소라',                261, 7,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/40/cover.jpg',  'songs/40/mr.mp3',  'songs/40/midi.json',  'songs/40/lyrics.txt',  NOW(6)),
(41,  '바람이 분다',                '이소라',                297, 6,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/41/cover.jpg',  'songs/41/mr.mp3',  'songs/41/midi.json',  'songs/41/lyrics.txt',  NOW(6)),
(42,  '바람기억',                   '나얼',                  268, 8,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/42/cover.jpg',  'songs/42/mr.mp3',  'songs/42/midi.json',  'songs/42/lyrics.txt',  NOW(6)),
(43,  '같은 시간 속의 너',          '나얼',                  272, 7,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/43/cover.jpg',  'songs/43/mr.mp3',  'songs/43/midi.json',  'songs/43/lyrics.txt',  NOW(6)),
(44,  '정말 사랑했을까',            '브라운 아이드 소울',    249, 7,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/44/cover.jpg',  'songs/44/mr.mp3',  'songs/44/midi.json',  'songs/44/lyrics.txt',  NOW(6)),
(45,  '이별택시',                   '김연우',                263, 7,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/45/cover.jpg',  'songs/45/mr.mp3',  'songs/45/midi.json',  'songs/45/lyrics.txt',  NOW(6)),
(46,  '취중진담',                   '김동률',                289, 6,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/46/cover.jpg',  'songs/46/mr.mp3',  'songs/46/midi.json',  'songs/46/lyrics.txt',  NOW(6)),
(47,  '다시 사랑한다 말할까',       '김동률',                302, 7,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/47/cover.jpg',  'songs/47/mr.mp3',  'songs/47/midi.json',  'songs/47/lyrics.txt',  NOW(6)),
(48,  '기억의 습작',                '전람회',                258, 5,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/48/cover.jpg',  'songs/48/mr.mp3',  'songs/48/midi.json',  'songs/48/lyrics.txt',  NOW(6)),
(49,  '여전히 아름다운지',          '토이',                  274, 6,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/49/cover.jpg',  'songs/49/mr.mp3',  'songs/49/midi.json',  'songs/49/lyrics.txt',  NOW(6)),
(50,  '다행이다',                   '이적',                  232, 4,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/50/cover.jpg',  'songs/50/mr.mp3',  'songs/50/midi.json',  'songs/50/lyrics.txt',  NOW(6)),
(51,  '거짓말 거짓말 거짓말',       '이적',                  240, 5,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/51/cover.jpg',  'songs/51/mr.mp3',  'songs/51/midi.json',  'songs/51/lyrics.txt',  NOW(6)),
(52,  '겁쟁이',                     '버즈',                  264, 8,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/52/cover.jpg',  'songs/52/mr.mp3',  'songs/52/midi.json',  'songs/52/lyrics.txt',  NOW(6)),
(53,  '가시',                       '버즈',                  253, 8,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/53/cover.jpg',  'songs/53/mr.mp3',  'songs/53/midi.json',  'songs/53/lyrics.txt',  NOW(6)),
(54,  '총 맞은 것처럼',             '백지영',                253, 8,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/54/cover.jpg',  'songs/54/mr.mp3',  'songs/54/midi.json',  'songs/54/lyrics.txt',  NOW(6)),
(55,  '사랑 안 해',                 '백지영',                261, 8,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/55/cover.jpg',  'songs/55/mr.mp3',  'songs/55/midi.json',  'songs/55/lyrics.txt',  NOW(6)),
(56,  '어른아이',                   '거미',                  258, 7,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/56/cover.jpg',  'songs/56/mr.mp3',  'songs/56/midi.json',  'songs/56/lyrics.txt',  NOW(6)),
(57,  '살다가',                     'SG워너비',              274, 8,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/57/cover.jpg',  'songs/57/mr.mp3',  'songs/57/midi.json',  'songs/57/lyrics.txt',  NOW(6)),
(58,  '라라라',                     'SG워너비',              262, 7,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/58/cover.jpg',  'songs/58/mr.mp3',  'songs/58/midi.json',  'songs/58/lyrics.txt',  NOW(6)),
(59,  'To Heaven',                  '조성모',                285, 7,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/59/cover.jpg',  'songs/59/mr.mp3',  'songs/59/midi.json',  'songs/59/lyrics.txt',  NOW(6)),
(60,  'Missing You',                '플라이 투 더 스카이',   258, 7,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/60/cover.jpg',  'songs/60/mr.mp3',  'songs/60/midi.json',  'songs/60/lyrics.txt',  NOW(6)),
(61,  '8282',                       '다비치',                226, 7,  'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/61/cover.jpg',  'songs/61/mr.mp3',  'songs/61/midi.json',  'songs/61/lyrics.txt',  NOW(6)),

-- ---------- 2010년대 이후 발라드 / 솔로 ----------
(62,  '시간아 멈춰라',              '다비치',                243, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/62/cover.jpg',  'songs/62/mr.mp3',  'songs/62/midi.json',  'songs/62/lyrics.txt',  NOW(6)),
(63,  '보여줄게',                   '에일리',                236, 9, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/63/cover.jpg',  'songs/63/mr.mp3',  'songs/63/midi.json',  'songs/63/lyrics.txt',  NOW(6)),
(64,  '첫눈처럼 너에게 가겠다',     '에일리',                275, 8, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/64/cover.jpg',  'songs/64/mr.mp3',  'songs/64/midi.json',  'songs/64/lyrics.txt',  NOW(6)),
(65,  '좋은 날',                    '아이유',                223, 8, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/65/cover.jpg',  'songs/65/mr.mp3',  'songs/65/midi.json',  'songs/65/lyrics.txt',  NOW(6)),
(66,  '밤편지',                     '아이유',                254, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/66/cover.jpg',  'songs/66/mr.mp3',  'songs/66/midi.json',  'songs/66/lyrics.txt',  NOW(6)),
(67,  '팔레트',                     '아이유',                215, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/67/cover.jpg',  'songs/67/mr.mp3',  'songs/67/midi.json',  'songs/67/lyrics.txt',  NOW(6)),
(68,  '만약에',                     '태연',                  231, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/68/cover.jpg',  'songs/68/mr.mp3',  'songs/68/midi.json',  'songs/68/lyrics.txt',  NOW(6)),
(69,  'INVU',                       '태연',                  214, 8, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/69/cover.jpg',  'songs/69/mr.mp3',  'songs/69/midi.json',  'songs/69/lyrics.txt',  NOW(6)),
(70,  '좋니',                       '윤종신',                246, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/70/cover.jpg',  'songs/70/mr.mp3',  'songs/70/midi.json',  'songs/70/lyrics.txt',  NOW(6)),
(71,  '오르막길',                   '정인',                  262, 9, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/71/cover.jpg',  'songs/71/mr.mp3',  'songs/71/midi.json',  'songs/71/lyrics.txt',  NOW(6)),
(72,  '모든 날, 모든 순간',         '폴킴',                  251, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/72/cover.jpg',  'songs/72/mr.mp3',  'songs/72/midi.json',  'songs/72/lyrics.txt',  NOW(6)),
(73,  '이 바보야',                  '정승환',                245, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/73/cover.jpg',  'songs/73/mr.mp3',  'songs/73/midi.json',  'songs/73/lyrics.txt',  NOW(6)),
(74,  '봄봄봄',                     '로이킴',                236, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/74/cover.jpg',  'songs/74/mr.mp3',  'songs/74/midi.json',  'songs/74/lyrics.txt',  NOW(6)),
(75,  '별 보러 가자',               '적재',                  232, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/75/cover.jpg',  'songs/75/mr.mp3',  'songs/75/midi.json',  'songs/75/lyrics.txt',  NOW(6)),
(76,  '아메리카노',                 '10CM',                  200, 4, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/76/cover.jpg',  'songs/76/mr.mp3',  'songs/76/midi.json',  'songs/76/lyrics.txt',  NOW(6)),
(77,  '선물',                       '멜로망스',              254, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/77/cover.jpg',  'songs/77/mr.mp3',  'songs/77/midi.json',  'songs/77/lyrics.txt',  NOW(6)),
(78,  '우주를 줄게',                '볼빨간사춘기',          226, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/78/cover.jpg',  'songs/78/mr.mp3',  'songs/78/midi.json',  'songs/78/lyrics.txt',  NOW(6)),
(79,  '200%',                       '악동뮤지션',            217, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/79/cover.jpg',  'songs/79/mr.mp3',  'songs/79/midi.json',  'songs/79/lyrics.txt',  NOW(6)),
(80,  '어떻게 이별까지 사랑하겠어, 널 사랑하는 거지', '악동뮤지션', 268, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/80/cover.jpg',  'songs/80/mr.mp3',  'songs/80/midi.json',  'songs/80/lyrics.txt',  NOW(6)),
(81,  '비도 오고 그래서',           '헤이즈',                218, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/81/cover.jpg',  'songs/81/mr.mp3',  'songs/81/midi.json',  'songs/81/lyrics.txt',  NOW(6)),
(82,  '다시 난, 여기',              '백예린',                233, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/82/cover.jpg',  'songs/82/mr.mp3',  'songs/82/midi.json',  'songs/82/lyrics.txt',  NOW(6)),
(83,  '벚꽃 엔딩',                  '버스커 버스커',         237, 4, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/83/cover.jpg',  'songs/83/mr.mp3',  'songs/83/midi.json',  'songs/83/lyrics.txt',  NOW(6)),
(84,  '여수 밤바다',                '버스커 버스커',         268, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/84/cover.jpg',  'songs/84/mr.mp3',  'songs/84/midi.json',  'songs/84/lyrics.txt',  NOW(6)),
(85,  '흔들리는 꽃들 속에서 네 샴푸향이 느껴진거야', '장범준', 224, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/85/cover.jpg',  'songs/85/mr.mp3',  'songs/85/midi.json',  'songs/85/lyrics.txt',  NOW(6)),
(86,  '마리아',                     '화사',                  192, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/86/cover.jpg',  'songs/86/mr.mp3',  'songs/86/midi.json',  'songs/86/lyrics.txt',  NOW(6)),

-- ---------- 록 / 밴드 / 인디 ----------
(87,  'Never Ending Story',         '부활',                  291, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/87/cover.jpg',  'songs/87/mr.mp3',  'songs/87/midi.json',  'songs/87/lyrics.txt',  NOW(6)),
(88,  '사랑할수록',                 '부활',                  285, 8, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/88/cover.jpg',  'songs/88/mr.mp3',  'songs/88/midi.json',  'songs/88/lyrics.txt',  NOW(6)),
(89,  '매직 카펫 라이드',           '자우림',                213, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/89/cover.jpg',  'songs/89/mr.mp3',  'songs/89/midi.json',  'songs/89/lyrics.txt',  NOW(6)),
(90,  '스물다섯, 스물하나',         '자우림',                247, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/90/cover.jpg',  'songs/90/mr.mp3',  'songs/90/midi.json',  'songs/90/lyrics.txt',  NOW(6)),
(91,  '기억을 걷는 시간',           '넬',                    305, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/91/cover.jpg',  'songs/91/mr.mp3',  'songs/91/midi.json',  'songs/91/lyrics.txt',  NOW(6)),
(92,  '나는 나비',                  'YB',                    261, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/92/cover.jpg',  'songs/92/mr.mp3',  'songs/92/midi.json',  'songs/92/lyrics.txt',  NOW(6)),
(93,  '말달리자',                   '크라잉넛',              172, 4, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/93/cover.jpg',  'songs/93/mr.mp3',  'songs/93/midi.json',  'songs/93/lyrics.txt',  NOW(6)),
(94,  '챠우챠우',                   '델리스파이스',          214, 4, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/94/cover.jpg',  'songs/94/mr.mp3',  'songs/94/midi.json',  'songs/94/lyrics.txt',  NOW(6)),
(95,  '넌 내게 반했어',             '노브레인',              208, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/95/cover.jpg',  'songs/95/mr.mp3',  'songs/95/midi.json',  'songs/95/lyrics.txt',  NOW(6)),
(96,  '달팽이',                     '패닉',                  253, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/96/cover.jpg',  'songs/96/mr.mp3',  'songs/96/midi.json',  'songs/96/lyrics.txt',  NOW(6)),
(97,  '아주 오래된 연인들',         '015B',                  264, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/97/cover.jpg',  'songs/97/mr.mp3',  'songs/97/midi.json',  'songs/97/lyrics.txt',  NOW(6)),
(98,  '텅 빈 거리에서',             '015B',                  276, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/98/cover.jpg',  'songs/98/mr.mp3',  'songs/98/midi.json',  'songs/98/lyrics.txt',  NOW(6)),
(99,  '주저하는 연인들을 위해',     '잔나비',                268, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/99/cover.jpg',  'songs/99/mr.mp3',  'songs/99/midi.json',  'songs/99/lyrics.txt',  NOW(6)),
(100, 'She',                        '잔나비',                244, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/100/cover.jpg', 'songs/100/mr.mp3', 'songs/100/midi.json', 'songs/100/lyrics.txt', NOW(6)),
(101, '위잉위잉',                   '혁오',                  220, 4, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/101/cover.jpg', 'songs/101/mr.mp3', 'songs/101/midi.json', 'songs/101/lyrics.txt', NOW(6)),
(102, '난춘',                       '새소년',                262, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/102/cover.jpg', 'songs/102/mr.mp3', 'songs/102/midi.json', 'songs/102/lyrics.txt', NOW(6)),
(103, '개화',                       'LUCY',                  226, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/103/cover.jpg', 'songs/103/mr.mp3', 'songs/103/midi.json', 'songs/103/lyrics.txt', NOW(6)),
(104, '예뻤어',                     'DAY6',                  224, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/104/cover.jpg', 'songs/104/mr.mp3', 'songs/104/midi.json', 'songs/104/lyrics.txt', NOW(6)),
(105, '한 페이지가 될 수 있게',     'DAY6',                  235, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/105/cover.jpg', 'songs/105/mr.mp3', 'songs/105/midi.json', 'songs/105/lyrics.txt', NOW(6)),
(106, 'Congratulations',            'DAY6',                  218, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/106/cover.jpg', 'songs/106/mr.mp3', 'songs/106/midi.json', 'songs/106/lyrics.txt', NOW(6)),
(107, '싸구려 커피',                '장기하와 얼굴들',       285, 4, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/107/cover.jpg', 'songs/107/mr.mp3', 'songs/107/midi.json', 'songs/107/lyrics.txt', NOW(6)),
(108, '거울',                       '국카스텐',              274, 8, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/108/cover.jpg', 'songs/108/mr.mp3', 'songs/108/midi.json', 'songs/108/lyrics.txt', NOW(6)),
(109, 'Everything',                 '검정치마',              250, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/109/cover.jpg', 'songs/109/mr.mp3', 'songs/109/midi.json', 'songs/109/lyrics.txt', NOW(6)),
(110, '옥탑방',                     'N.Flying',              233, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/110/cover.jpg', 'songs/110/mr.mp3', 'songs/110/midi.json', 'songs/110/lyrics.txt', NOW(6)),
(111, '외톨이야',                   'CNBLUE',                218, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/111/cover.jpg', 'songs/111/mr.mp3', 'songs/111/midi.json', 'songs/111/lyrics.txt', NOW(6)),

-- ---------- 90년대 댄스 / 가요 ----------
(112, '난 알아요',                  '서태지와 아이들',       234, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/112/cover.jpg', 'songs/112/mr.mp3', 'songs/112/midi.json', 'songs/112/lyrics.txt', NOW(6)),
(113, '하여가',                     '서태지와 아이들',       251, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/113/cover.jpg', 'songs/113/mr.mp3', 'songs/113/midi.json', 'songs/113/lyrics.txt', NOW(6)),
(114, '컴백홈',                     '서태지와 아이들',       279, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/114/cover.jpg', 'songs/114/mr.mp3', 'songs/114/midi.json', 'songs/114/lyrics.txt', NOW(6)),
(115, '잘못된 만남',                '김건모',                250, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/115/cover.jpg', 'songs/115/mr.mp3', 'songs/115/midi.json', 'songs/115/lyrics.txt', NOW(6)),
(116, '핑계',                       '김건모',                246, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/116/cover.jpg', 'songs/116/mr.mp3', 'songs/116/midi.json', 'songs/116/lyrics.txt', NOW(6)),
(117, '날개 잃은 천사',             '룰라',                  242, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/117/cover.jpg', 'songs/117/mr.mp3', 'songs/117/midi.json', 'songs/117/lyrics.txt', NOW(6)),
(118, 'DOC와 춤을',                 'DJ DOC',                262, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/118/cover.jpg', 'songs/118/mr.mp3', 'songs/118/midi.json', 'songs/118/lyrics.txt', NOW(6)),
(119, 'Run To You',                 'DJ DOC',                250, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/119/cover.jpg', 'songs/119/mr.mp3', 'songs/119/midi.json', 'songs/119/lyrics.txt', NOW(6)),
(120, '꿍따리 샤바라',              '클론',                  224, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/120/cover.jpg', 'songs/120/mr.mp3', 'songs/120/midi.json', 'songs/120/lyrics.txt', NOW(6)),
(121, '회상',                       '터보',                  244, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/121/cover.jpg', 'songs/121/mr.mp3', 'songs/121/midi.json', 'songs/121/lyrics.txt', NOW(6)),
(122, '검은 고양이 네로',           '터보',                  218, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/122/cover.jpg', 'songs/122/mr.mp3', 'songs/122/midi.json', 'songs/122/lyrics.txt', NOW(6)),
(123, '여름 안에서',                '듀스',                  240, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/123/cover.jpg', 'songs/123/mr.mp3', 'songs/123/midi.json', 'songs/123/lyrics.txt', NOW(6)),
(124, '애상',                       '쿨',                    245, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/124/cover.jpg', 'songs/124/mr.mp3', 'songs/124/midi.json', 'songs/124/lyrics.txt', NOW(6)),
(125, '아로하',                     '쿨',                    253, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/125/cover.jpg', 'songs/125/mr.mp3', 'songs/125/midi.json', 'songs/125/lyrics.txt', NOW(6)),
(126, '순정',                       '코요태',                241, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/126/cover.jpg', 'songs/126/mr.mp3', 'songs/126/midi.json', 'songs/126/lyrics.txt', NOW(6)),
(127, '이별공식',                   'R.ef',                  229, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/127/cover.jpg', 'songs/127/mr.mp3', 'songs/127/midi.json', 'songs/127/lyrics.txt', NOW(6)),
(128, '날 떠나지마',                '박진영',                251, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/128/cover.jpg', 'songs/128/mr.mp3', 'songs/128/midi.json', 'songs/128/lyrics.txt', NOW(6)),
(129, '어머님이 누구니',            '박진영',                226, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/129/cover.jpg', 'songs/129/mr.mp3', 'songs/129/midi.json', 'songs/129/lyrics.txt', NOW(6)),
(130, '배반의 장미',                '엄정화',                243, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/130/cover.jpg', 'songs/130/mr.mp3', 'songs/130/midi.json', 'songs/130/lyrics.txt', NOW(6)),
(131, '10 Minutes',                 '이효리',                216, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/131/cover.jpg', 'songs/131/mr.mp3', 'songs/131/midi.json', 'songs/131/lyrics.txt', NOW(6)),

-- ---------- 1~2세대 아이돌 ----------
(132, '캔디',                       'H.O.T.',                232, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/132/cover.jpg', 'songs/132/mr.mp3', 'songs/132/midi.json', 'songs/132/lyrics.txt', NOW(6)),
(133, '행복',                       'H.O.T.',                258, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/133/cover.jpg', 'songs/133/mr.mp3', 'songs/133/midi.json', 'songs/133/lyrics.txt', NOW(6)),
(134, '커플',                       '젝스키스',              249, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/134/cover.jpg', 'songs/134/mr.mp3', 'songs/134/midi.json', 'songs/134/lyrics.txt', NOW(6)),
(135, 'I''m Your Girl',             'S.E.S.',                224, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/135/cover.jpg', 'songs/135/mr.mp3', 'songs/135/midi.json', 'songs/135/lyrics.txt', NOW(6)),
(136, '영원한 사랑',                '핑클',                  246, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/136/cover.jpg', 'songs/136/mr.mp3', 'songs/136/midi.json', 'songs/136/lyrics.txt', NOW(6)),
(137, '어머님께',                   'god',                   275, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/137/cover.jpg', 'songs/137/mr.mp3', 'songs/137/midi.json', 'songs/137/lyrics.txt', NOW(6)),
(138, '길',                         'god',                   282, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/138/cover.jpg', 'songs/138/mr.mp3', 'songs/138/midi.json', 'songs/138/lyrics.txt', NOW(6)),
(139, 'Perfect Man',                '신화',                  231, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/139/cover.jpg', 'songs/139/mr.mp3', 'songs/139/midi.json', 'songs/139/lyrics.txt', NOW(6)),
(140, 'Hug',                        '동방신기',              253, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/140/cover.jpg', 'songs/140/mr.mp3', 'songs/140/midi.json', 'songs/140/lyrics.txt', NOW(6)),
(141, 'Rising Sun',                 '동방신기',              268, 8, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/141/cover.jpg', 'songs/141/mr.mp3', 'songs/141/midi.json', 'songs/141/lyrics.txt', NOW(6)),
(142, 'Sorry Sorry',                '슈퍼주니어',            232, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/142/cover.jpg', 'songs/142/mr.mp3', 'songs/142/midi.json', 'songs/142/lyrics.txt', NOW(6)),
(143, '링딩동',                     '샤이니',                210, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/143/cover.jpg', 'songs/143/mr.mp3', 'songs/143/midi.json', 'songs/143/lyrics.txt', NOW(6)),
(144, 'Heartbeat',                  '2PM',                   216, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/144/cover.jpg', 'songs/144/mr.mp3', 'songs/144/midi.json', 'songs/144/lyrics.txt', NOW(6)),
(145, 'Fiction',                    '비스트',                253, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/145/cover.jpg', 'songs/145/mr.mp3', 'songs/145/midi.json', 'songs/145/lyrics.txt', NOW(6)),
(146, '내꺼하자',                   '인피니트',              231, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/146/cover.jpg', 'songs/146/mr.mp3', 'songs/146/midi.json', 'songs/146/lyrics.txt', NOW(6)),
(147, '하루하루',                   '빅뱅',                  254, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/147/cover.jpg', 'songs/147/mr.mp3', 'songs/147/midi.json', 'songs/147/lyrics.txt', NOW(6)),
(148, 'Fantastic Baby',             '빅뱅',                  232, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/148/cover.jpg', 'songs/148/mr.mp3', 'songs/148/midi.json', 'songs/148/lyrics.txt', NOW(6)),
(149, 'I Don''t Care',              '2NE1',                  234, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/149/cover.jpg', 'songs/149/mr.mp3', 'songs/149/midi.json', 'songs/149/lyrics.txt', NOW(6)),
(150, '내가 제일 잘 나가',          '2NE1',                  195, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/150/cover.jpg', 'songs/150/mr.mp3', 'songs/150/midi.json', 'songs/150/lyrics.txt', NOW(6)),
(151, 'Gee',                        '소녀시대',              194, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/151/cover.jpg', 'songs/151/mr.mp3', 'songs/151/midi.json', 'songs/151/lyrics.txt', NOW(6)),
(152, '다시 만난 세계',             '소녀시대',              271, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/152/cover.jpg', 'songs/152/mr.mp3', 'songs/152/midi.json', 'songs/152/lyrics.txt', NOW(6)),
(153, 'Tell Me',                    '원더걸스',              219, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/153/cover.jpg', 'songs/153/mr.mp3', 'songs/153/midi.json', 'songs/153/lyrics.txt', NOW(6)),
(154, '미스터',                     '카라',                  212, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/154/cover.jpg', 'songs/154/mr.mp3', 'songs/154/midi.json', 'songs/154/lyrics.txt', NOW(6)),
(155, 'Abracadabra',                '브라운 아이드 걸스',    218, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/155/cover.jpg', 'songs/155/mr.mp3', 'songs/155/midi.json', 'songs/155/lyrics.txt', NOW(6)),
(156, 'Touch My Body',              '씨스타',                214, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/156/cover.jpg', 'songs/156/mr.mp3', 'songs/156/midi.json', 'songs/156/lyrics.txt', NOW(6)),

-- ---------- 3~4세대 아이돌 ----------
(157, 'NoNoNo',                     '에이핑크',              219, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/157/cover.jpg', 'songs/157/mr.mp3', 'songs/157/midi.json', 'songs/157/lyrics.txt', NOW(6)),
(158, '위아래',                     'EXID',                  212, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/158/cover.jpg', 'songs/158/mr.mp3', 'songs/158/midi.json', 'songs/158/lyrics.txt', NOW(6)),
(159, '오늘부터 우리는',            '여자친구',              213, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/159/cover.jpg', 'songs/159/mr.mp3', 'songs/159/midi.json', 'songs/159/lyrics.txt', NOW(6)),
(160, '봄날',                       '방탄소년단',            274, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/160/cover.jpg', 'songs/160/mr.mp3', 'songs/160/midi.json', 'songs/160/lyrics.txt', NOW(6)),
(161, 'DNA',                        '방탄소년단',            223, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/161/cover.jpg', 'songs/161/mr.mp3', 'songs/161/midi.json', 'songs/161/lyrics.txt', NOW(6)),
(162, 'Dynamite',                   '방탄소년단',            199, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/162/cover.jpg', 'songs/162/mr.mp3', 'songs/162/midi.json', 'songs/162/lyrics.txt', NOW(6)),
(163, '으르렁',                     '엑소',                  210, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/163/cover.jpg', 'songs/163/mr.mp3', 'songs/163/midi.json', 'songs/163/lyrics.txt', NOW(6)),
(164, 'Love Shot',                  '엑소',                  189, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/164/cover.jpg', 'songs/164/mr.mp3', 'songs/164/midi.json', 'songs/164/lyrics.txt', NOW(6)),
(165, '아주 NICE',                  '세븐틴',                217, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/165/cover.jpg', 'songs/165/mr.mp3', 'songs/165/midi.json', 'songs/165/lyrics.txt', NOW(6)),
(166, '손오공',                     '세븐틴',                197, 8, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/166/cover.jpg', 'songs/166/mr.mp3', 'songs/166/midi.json', 'songs/166/lyrics.txt', NOW(6)),
(167, '神메뉴',                     '스트레이 키즈',         194, 8, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/167/cover.jpg', 'songs/167/mr.mp3', 'songs/167/midi.json', 'songs/167/lyrics.txt', NOW(6)),
(168, '0X1=LOVESONG',               '투모로우바이투게더',    200, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/168/cover.jpg', 'songs/168/mr.mp3', 'songs/168/midi.json', 'songs/168/lyrics.txt', NOW(6)),
(169, 'TT',                         '트와이스',              213, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/169/cover.jpg', 'songs/169/mr.mp3', 'songs/169/midi.json', 'songs/169/lyrics.txt', NOW(6)),
(170, 'Cheer Up',                   '트와이스',              196, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/170/cover.jpg', 'songs/170/mr.mp3', 'songs/170/midi.json', 'songs/170/lyrics.txt', NOW(6)),
(171, '빨간 맛',                    '레드벨벳',              191, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/171/cover.jpg', 'songs/171/mr.mp3', 'songs/171/midi.json', 'songs/171/lyrics.txt', NOW(6)),
(172, 'Psycho',                     '레드벨벳',              214, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/172/cover.jpg', 'songs/172/mr.mp3', 'songs/172/midi.json', 'songs/172/lyrics.txt', NOW(6)),
(173, '뚜두뚜두',                   '블랙핑크',              208, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/173/cover.jpg', 'songs/173/mr.mp3', 'songs/173/midi.json', 'songs/173/lyrics.txt', NOW(6)),
(174, 'How You Like That',          '블랙핑크',              181, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/174/cover.jpg', 'songs/174/mr.mp3', 'songs/174/midi.json', 'songs/174/lyrics.txt', NOW(6)),
(175, 'LOVE DIVE',                  '아이브',                176, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/175/cover.jpg', 'songs/175/mr.mp3', 'songs/175/midi.json', 'songs/175/lyrics.txt', NOW(6)),
(176, 'After LIKE',                 '아이브',                175, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/176/cover.jpg', 'songs/176/mr.mp3', 'songs/176/midi.json', 'songs/176/lyrics.txt', NOW(6)),
(177, 'Hype Boy',                   '뉴진스',                179, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/177/cover.jpg', 'songs/177/mr.mp3', 'songs/177/midi.json', 'songs/177/lyrics.txt', NOW(6)),
(178, 'Ditto',                      '뉴진스',                185, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/178/cover.jpg', 'songs/178/mr.mp3', 'songs/178/midi.json', 'songs/178/lyrics.txt', NOW(6)),
(179, 'ANTIFRAGILE',                '르세라핌',              187, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/179/cover.jpg', 'songs/179/mr.mp3', 'songs/179/midi.json', 'songs/179/lyrics.txt', NOW(6)),
(180, 'Next Level',                 '에스파',                223, 8, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/180/cover.jpg', 'songs/180/mr.mp3', 'songs/180/midi.json', 'songs/180/lyrics.txt', NOW(6)),
(181, 'Supernova',                  '에스파',                178, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/181/cover.jpg', 'songs/181/mr.mp3', 'songs/181/midi.json', 'songs/181/lyrics.txt', NOW(6)),

-- ---------- 솔로 / 힙합 / R&B ----------
(182, 'TOMBOY',                     '(여자)아이들',          175, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/182/cover.jpg', 'songs/182/mr.mp3', 'songs/182/midi.json', 'songs/182/lyrics.txt', NOW(6)),
(183, '퀸카',                       '(여자)아이들',          174, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/183/cover.jpg', 'songs/183/mr.mp3', 'songs/183/midi.json', 'songs/183/lyrics.txt', NOW(6)),
(184, '살짝 설렜어',                '오마이걸',              199, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/184/cover.jpg', 'songs/184/mr.mp3', 'songs/184/midi.json', 'songs/184/lyrics.txt', NOW(6)),
(185, '달라달라',                   'ITZY',                  196, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/185/cover.jpg', 'songs/185/mr.mp3', 'songs/185/midi.json', 'songs/185/lyrics.txt', NOW(6)),
(186, 'HIP',                        '마마무',                195, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/186/cover.jpg', 'songs/186/mr.mp3', 'songs/186/midi.json', 'songs/186/lyrics.txt', NOW(6)),
(187, '가시나',                     '선미',                  193, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/187/cover.jpg', 'songs/187/mr.mp3', 'songs/187/midi.json', 'songs/187/lyrics.txt', NOW(6)),
(188, '벌써 12시',                  '청하',                  197, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/188/cover.jpg', 'songs/188/mr.mp3', 'songs/188/midi.json', 'songs/188/lyrics.txt', NOW(6)),
(189, 'No.1',                       '보아',                  240, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/189/cover.jpg', 'songs/189/mr.mp3', 'songs/189/midi.json', 'songs/189/lyrics.txt', NOW(6)),
(190, '태양을 피하는 방법',         '비',                    245, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/190/cover.jpg', 'songs/190/mr.mp3', 'songs/190/midi.json', 'songs/190/lyrics.txt', NOW(6)),
(191, '유혹의 소나타',              '아이비',                217, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/191/cover.jpg', 'songs/191/mr.mp3', 'songs/191/midi.json', 'songs/191/lyrics.txt', NOW(6)),
(192, '강남스타일',                 '싸이',                  219, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/192/cover.jpg', 'songs/192/mr.mp3', 'songs/192/midi.json', 'songs/192/lyrics.txt', NOW(6)),
(193, '우산',                       '에픽하이',              254, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/193/cover.jpg', 'songs/193/mr.mp3', 'songs/193/midi.json', 'songs/193/lyrics.txt', NOW(6)),
(194, 'Fly',                        '에픽하이',              234, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/194/cover.jpg', 'songs/194/mr.mp3', 'songs/194/midi.json', 'songs/194/lyrics.txt', NOW(6)),
(195, '죽일 놈',                    '다이나믹 듀오',         245, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/195/cover.jpg', 'songs/195/mr.mp3', 'songs/195/midi.json', 'songs/195/lyrics.txt', NOW(6)),
(196, '광대',                       '리쌍',                  251, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/196/cover.jpg', 'songs/196/mr.mp3', 'songs/196/midi.json', 'songs/196/lyrics.txt', NOW(6)),
(197, '아쿠아 맨',                  '빈지노',                232, 8, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/197/cover.jpg', 'songs/197/mr.mp3', 'songs/197/midi.json', 'songs/197/lyrics.txt', NOW(6)),
(198, '아무노래',                   '지코',                  219, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/198/cover.jpg', 'songs/198/mr.mp3', 'songs/198/midi.json', 'songs/198/lyrics.txt', NOW(6)),
(199, '잠깐 시간 될까',             '크러쉬',                213, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/199/cover.jpg', 'songs/199/mr.mp3', 'songs/199/midi.json', 'songs/199/lyrics.txt', NOW(6)),
(200, '인스타그램',                 'DEAN',                  217, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/200/cover.jpg', 'songs/200/mr.mp3', 'songs/200/midi.json', 'songs/200/lyrics.txt', NOW(6)),
(201, '양화대교',                   '자이언티',              229, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/201/cover.jpg', 'songs/201/mr.mp3', 'songs/201/midi.json', 'songs/201/lyrics.txt', NOW(6)),

-- ---------- 트로트 / 성인가요 ----------
(202, '사랑은 늘 도망가',           '임영웅',                246, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/202/cover.jpg', 'songs/202/mr.mp3', 'songs/202/midi.json', 'songs/202/lyrics.txt', NOW(6)),
(203, '이제 나만 믿어요',           '임영웅',                257, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/203/cover.jpg', 'songs/203/mr.mp3', 'songs/203/midi.json', 'songs/203/lyrics.txt', NOW(6)),
(204, '소주 한 잔',                 '임창정',                271, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/204/cover.jpg', 'songs/204/mr.mp3', 'songs/204/midi.json', 'songs/204/lyrics.txt', NOW(6)),
(205, '어머나',                     '장윤정',                213, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/205/cover.jpg', 'songs/205/mr.mp3', 'songs/205/midi.json', 'songs/205/lyrics.txt', NOW(6)),
(206, '초혼',                       '장윤정',                231, 7, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/206/cover.jpg', 'songs/206/mr.mp3', 'songs/206/midi.json', 'songs/206/lyrics.txt', NOW(6)),
(207, '사랑의 배터리',              '홍진영',                208, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/207/cover.jpg', 'songs/207/mr.mp3', 'songs/207/midi.json', 'songs/207/lyrics.txt', NOW(6)),
(208, '테스형!',                    '나훈아',                232, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/208/cover.jpg', 'songs/208/mr.mp3', 'songs/208/midi.json', 'songs/208/lyrics.txt', NOW(6)),
(209, '아모르 파티',                '김연자',                224, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/209/cover.jpg', 'songs/209/mr.mp3', 'songs/209/midi.json', 'songs/209/lyrics.txt', NOW(6)),
(210, '내 나이가 어때서',           '오승근',                218, 5, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/210/cover.jpg', 'songs/210/mr.mp3', 'songs/210/midi.json', 'songs/210/lyrics.txt', NOW(6)),
(211, '안동역에서',                 '진성',                  235, 6, 'https://ssasukae-assets.s3.ap-northeast-2.amazonaws.com/songs/211/cover.jpg', 'songs/211/mr.mp3', 'songs/211/midi.json', 'songs/211/lyrics.txt', NOW(6));

-- AUTO_INCREMENT 를 더미 데이터 뒤로 밀어 둠 (이후 정상 등록 시 충돌 방지)
ALTER TABLE songs AUTO_INCREMENT = 212;
